### ISSUE TITLE
Pelagus Extension / Meta Mask Problem

### ISSUE THREAD

**Issue by Why-x-Phy** [PelagusWallet/pelagus-extension#112]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

When I try to connect to my Meta Mask wallet on any site, the Pelagus extension always comes up. I can therefore no longer use MetaMask

### What did not work?

When I try to connect to my Meta Mask wallet on any site, the Pelagus extension always comes up. I can therefore no longer use MetaMask

### Version

None

### Relevant log output

```shell
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36


[2023-10-10T12:25:18.767Z] [INFO:BG] SerialFallbackProvider.reconnectProvider
    No error but setting backoff: 1200 ms. URL: https://rpc.cyprus2.colosseum.quaiscan.io
        at SerialFallbackProvider.reconnectProvider (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81551:26)


[2023-10-10T12:29:25.828Z] [ERROR:BG] SerialFallbackProvider.attemptToReconnectToPrimaryProvider
    Could not detect network; trying again in 10000 ms. URL: http://localhost:8614
        at SerialFallbackProvider.attemptToReconnectToPrimaryProvider (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81603:28)


[2023-10-10T12:29:45.828Z] [ERROR:BG] SerialFallbackProvider.attemptToReconnectToPrimaryProvider
    Could not detect network; trying again in 10000 ms. URL: http://localhost:8614
        at SerialFallbackProvider.attemptToReconnectToPrimaryProvider (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81603:28)


[2023-10-10T12:30:05.822Z] [ERROR:BG] SerialFallbackProvider.attemptToReconnectToPrimaryProvider
    Could not detect network; trying again in 10000 ms. URL: http://localhost:8614
        at SerialFallbackProvider.attemptToReconnectToPrimaryProvider (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81603:28)


[2023-10-10T12:30:25.821Z] [ERROR:BG] SerialFallbackProvider.attemptToReconnectToPrimaryProvider
    Could not detect network; trying again in 10000 ms. URL: http://localhost:8614
        at SerialFallbackProvider.attemptToReconnectToPrimaryProvider (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81603:28)


[2023-10-10T12:30:45.833Z] [ERROR:BG] SerialFallbackProvider.attemptToReconnectToPrimaryProvider
    Could not detect network; trying again in 10000 ms. URL: http://localhost:8614
        at SerialFallbackProvider.attemptToReconnectToPrimaryProvider (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81603:28)
```

**Comment by jdowning100** [comment]
Both MetaMask and Pelagus compete for the same API calls from dApps. You can not run them at the same time. Just turn off Pelagus or Metamask when you want to use one over the other.
