### ISSUE TITLE
Pelagus Wallet never initializes after signup flow

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/pelagus-extension#147]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Create a new wallet with a new seed in Pelagus.

### What did not work?

Upon finishing the initial seed verification, the Pelagus site lands on a page that says "Account Added to Pelagus". When you reach this page, clicking on the extension immediately closes it and returns you to the same web page.  The page looks like this: 
![Screenshot 2024-03-19 at 1 48 54 PM](https://github.com/PelagusWallet/pelagus-extension/assets/98721462/1101ae0c-226b-46a6-aaef-0e48211a7535)

The issue seems to be non-deterministic as this flow works some of the time, but not all.

The correct flow lands you on a page that looks like this: 
![Screenshot 2024-03-19 at 11 55 43 AM](https://github.com/PelagusWallet/pelagus-extension/assets/98721462/733b703e-6fad-400e-b800-926174fcec32)

### Version

None

### Relevant log output

```shell
logger.ts:210 Async thunk failed Error: KeyringService must be unlocked.
    at KeyringService.requireUnlocked (index.ts:286:13)
    at KeyringService.persistKeyrings (index.ts:717:10)
    at KeyringService.importKeyring (index.ts:353:16)
    at main.ts:1498:35
    at index.js:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.js:304:23)
    at async keyrings.ts:56:65
    at async utils.ts:129:9
logEvent@logger.ts:210
```

**Comment by Juuddi** [comment]
This issue elaborates on the issue noted in #143 by @maxbibeau.

It should be noted that during a successful setup, there is a console log that notes that the `KeyringService` is unlocked. When the setup is unsuccessful, there is a console error that notes the `KeyringService` must be unlocked.
