### ISSUE TITLE
Adding new address: extension crashes if region was typed incorrectly

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#24]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Adding new address to the existing wallet, when user is prompted to type shard.
**Steps to reproduce:**
1. Click add new address;
2. Type shard that doesn't relates to any existing one(e.g. cprs-4);
3. Click New address button;
4. Click somwere outside of extension to hide it;
5. Click to open it again;

### What did not work?

UI is absent, only background color is diaplyed.

### Version

v0.38.1

### Relevant log output

```shell
Uncaught (in promise) Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":45,\"error\":{\"code\":-32000,\"message\":\"address is not in scope\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"quai_getCode\",\"params\":[\"0x2892e91f28e5cf3e91873724b7e237f871f24019\",\"latest\"],\"id\":45,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.hydra2.colosseum.quaiscan.io", code=SERVER_ERROR, version=web/0.1.0)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at index.js:261:1
    at Generator.next (<anonymous>)
    at fulfilled (index.js:5:43)
makeError @ index.js:224
throwError @ index.js:233
(anonymous) @ index.js:261
fulfilled @ index.js:5
await in fulfilled (async)
enrichActivities @ main.ts:809
await in enrichActivities (async)
(anonymous) @ main.ts:1638
(anonymous) @ index.js:306
emit @ index.js:304
await in emit (async)
(anonymous) @ ui.ts:249
await in (anonymous) (async)
(anonymous) @ utils.ts:129
(anonymous) @ redux-toolkit.esm.js:1112
step @ redux-toolkit.esm.js:38
(anonymous) @ redux-toolkit.esm.js:19
(anonymous) @ redux-toolkit.esm.js:87
__async @ redux-toolkit.esm.js:69
(anonymous) @ redux-toolkit.esm.js:1096
(anonymous) @ redux-toolkit.esm.js:1150
(anonymous) @ index.js:8
(anonymous) @ redux-toolkit.esm.js:314
(anonymous) @ alias.js:20
dispatchResponse @ wrapStore.js:94
(anonymous) @ serialization.js:38
```

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/21

**Comment by Friedheilm** [comment]
Validation error is displayed now. Fix verified.
