### ISSUE TITLE
Pelagus wallet keeps opening with blank screen

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#429]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Opening the wallet extension shows a blank screen and an error in the console:

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ih (react-dom.production.min.js:158:173)
    at Object.Th [as useRef] (react-dom.production.min.js:166:340)
    at exports.useRef (react.production.min.js:23:230)
    at useTranslation_useTranslation (useTranslation.js:69:19)
    at GlobalModal (GlobalModal.tsx:12:17)
    at Ch (react-dom.production.min.js:157:137)
    at li (react-dom.production.min.js:180:154)
    at ck (react-dom.production.min.js:269:343)
    at bk (react-dom.production.min.js:250:347)
    at ak (react-dom.production.min.js:250:278)
Ni @ react-dom.production.min.js:216Understand this errorAI
react-dom.production.min.js:158 Uncaught (in promise) Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ih (react-dom.production.min.js:158:173)
    at Object.Th [as useRef] (react-dom.production.min.js:166:340)
    at exports.useRef (react.production.min.js:23:230)
    at useTranslation_useTranslation (useTranslation.js:69:19)
    at GlobalModal (GlobalModal.tsx:12:17)
    at Ch (react-dom.production.min.js:157:137)
    at li (react-dom.production.min.js:180:154)
    at ck (react-dom.production.min.js:269:343)
    at bk (react-dom.production.min.js:250:347)
    at ak (react-dom.production.min.js:250:278)

### What did not work?

Unable to open the wallet/extension. Restarting the extension fixes it temporarily, after about 10 min the problem resurfaces.

### Version

None

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Ay')
    at startMain (index.ts:38:29)
    at 2028 (background.ts:61:1)
    at __webpack_require__ (bootstrap:19:32)
    at 3664 (utxo-activities-utils.ts:128:24)
    at __webpack_require__ (bootstrap:19:32)
    at 5385 (type-guards.ts:38:1)
    at __webpack_require__ (bootstrap:19:32)
    at 5764 (features.ts:109:1)
    at __webpack_require__ (bootstrap:19:32)
    at node module decorator:4:15

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ih (react-dom.production.min.js:158:173)
    at Kh (react-dom.production.min.js:159:22)
    at Object.useState (react-dom.production.min.js:174:261)
    at exports.useState (react.production.min.js:23:281)
    at useTranslation_useTranslation (useTranslation.js:62:19)
    at SharedDrawer (SharedDrawer.tsx:58:26)
    at Ch (react-dom.production.min.js:157:137)
    at li (react-dom.production.min.js:180:154)
    at ck (react-dom.production.min.js:269:343)
    at bk (react-dom.production.min.js:250:347)
Ni @ react-dom.production.min.js:216
Pi.c.callback @ react-dom.production.min.js:216
Eg @ react-dom.production.min.js:131
Yi @ react-dom.production.min.js:220
dk @ react-dom.production.min.js:259
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
Jg @ react-dom.production.min.js:237
Oh @ react-dom.production.min.js:170
(anonymous) @ dom-hooks.ts:59
setTimeout
(anonymous) @ dom-hooks.ts:58
fk @ react-dom.production.min.js:262
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Oj @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
V @ scheduler.production.min.js:16
F.port1.onmessage @ scheduler.production.min.js:12Understand this errorAI
react-dom.production.min.js:158 Uncaught Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ih (react-dom.production.min.js:158:173)
    at Kh (react-dom.production.min.js:159:22)
    at Object.useState (react-dom.production.min.js:174:261)
    at exports.useState (react.production.min.js:23:281)
    at useTranslation_useTranslation (useTranslation.js:62:19)
    at SharedDrawer (SharedDrawer.tsx:58:26)
    at Ch (react-dom.production.min.js:157:137)
    at li (react-dom.production.min.js:180:154)
    at ck (react-dom.production.min.js:269:343)
    at bk (react-dom.production.min.js:250:347)
```

**Comment by mark8700-bit** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Berge511** [comment]
Hello @jdowning100  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
