### ISSUE TITLE
Sending transaction: amount equal to wallet balance shouldn't be accepted

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#57]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

**Steps to reproduce:**
1. Initialize sending transaction;
2. In "Amount" field indicate same value as user balance;
3. Enter recipient address;
4. Click "Continue" button;

**Actual result:** user is directed to the same screen, as if transaction sending was successful. 

### What did not work?

**Expected result:** I can suggest 2 option to handle this case

- Continue button shouldn't be unlocked and value used for limiting amount should be adjusted to include fee for the transaction.
- Given error should be processed and keep user on send screen and give notification that user doesn't have enough funds to pay for fee. 

### Version

v0.38.1

### Relevant log output

```shell
Skipping fallback for unidentified error Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":411,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"quai_sendRawTransaction\",\"params\":[\"0x00f87682232880843b9aca00843b9aca07830186a094114e43d552cc9c404bbdadd2ac08446f66a9db1d89d8d726b7177a80000080c001a0c205c72fb4bd4439a6470371e6c0b0e6df05d40699d0da1c61768fcec1322365a003307256f3eac0014a67477a6aaea826eefc70a48b2a803db265d6f6985521bc\"],\"id\":411,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.cyprus1.colosseum.quaiscan.io", code=SERVER_ERROR, version=web/0.1.0)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at index.js:261:1
    at Generator.next (<anonymous>)
    at fulfilled (index.js:5:43) Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":411,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"quai_sendRawTransaction\",\"params\":[\"0x00f87682232880843b9aca00843b9aca07830186a094114e43d552cc9c404bbdadd2ac08446f66a9db1d89d8d726b7177a80000080c001a0c205c72fb4bd4439a6470371e6c0b0e6df05d40699d0da1c61768fcec1322365a003307256f3eac0014a67477a6aaea826eefc70a48b2a803db265d6f6985521bc\"],\"id\":411,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.cyprus1.colosseum.quaiscan.io", code=SERVER_ERROR, version=web/0.1.0)
    at Logger.makeError (chrome-extension://gdnpnedmjcfhgokohcgocjclepjijcaf/background.js:45169:23)
    at Logger.throwError (chrome-extension://gdnpnedmjcfhgokohcgocjclepjijcaf/background.js:45178:20)
    at chrome-extension://gdnpnedmjcfhgokohcgocjclepjijcaf/background.js:57763:32
    at Generator.next (<anonymous>)
    at fulfilled (chrome-extension://gdnpnedmjcfhgokohcgocjclepjijcaf/background.js:57507:58)
routeRpcCall @ serial-fallback-provider.ts:401
await in routeRpcCall (async)
send @ serial-fallback-provider.ts:546
(anonymous) @ json-rpc-provider.js:602
(anonymous) @ json-rpc-provider.js:8
(anonymous) @ json-rpc-provider.js:4
perform @ json-rpc-provider.js:579
(anonymous) @ base-provider.js:1394
fulfilled @ base-provider.js:5
Promise.then (async)
step @ base-provider.js:7
fulfilled @ base-provider.js:5
Promise.then (async)
step @ base-provider.js:7
fulfilled @ base-provider.js:5
Promise.then (async)
step @ base-provider.js:7
(anonymous) @ base-provider.js:8
(anonymous) @ base-provider.js:4
sendTransaction @ base-provider.js:1385
(anonymous) @ assets.ts:525
(anonymous) @ index.js:306
emit @ index.js:304
await in emit (async)
(anonymous) @ main.ts:968
setTimeout (async)
(anonymous) @ main.ts:968
await in (anonymous) (async)
(anonymous) @ index.js:306
emit @ index.js:304
await in emit (async)
signData @ assets.ts:541
(anonymous) @ assets.ts:308
(anonymous) @ utils.ts:129
(anonymous) @ redux-toolkit.esm.js:1112
step @ redux-toolkit.esm.js:38
(anonymous) @ redux-toolkit.esm.js:19
(anonymous) @ redux-toolkit.esm.js:87
__async @ redux-toolkit.esm.js:69
(anonymous) @ redux-toolkit.esm.js:1096
(anonymous) @ redux-toolkit.esm.js:1150
(anonymous) @ index.js:8
(anonymous) @ redux-toolkit.esm.js:314
(anonymous) @ alias.js:20
dispatchResponse @ wrapStore.js:94
(anonymous) @ serialization.js:38
index.js:224 Uncaught (in promise) Error: insufficient funds for intrinsic transaction cost [ See: https://links.quais.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":411,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"quai_sendRawTransaction\",\"params\":[\"0x00f87682232880843b9aca00843b9aca07830186a094114e43d552cc9c404bbdadd2ac08446f66a9db1d89d8d726b7177a80000080c001a0c205c72fb4bd4439a6470371e6c0b0e6df05d40699d0da1c61768fcec1322365a003307256f3eac0014a67477a6aaea826eefc70a48b2a803db265d6f6985521bc\"],\"id\":411,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.cyprus1.colosseum.quaiscan.io"}, method="sendTransaction", transaction="0x00f87682232880843b9aca00843b9aca07830186a094114e43d552cc9c404bbdadd2ac08446f66a9db1d89d8d726b7177a80000080c001a0c205c72fb4bd4439a6470371e6c0b0e6df05d40699d0da1c61768fcec1322365a003307256f3eac0014a67477a6aaea826eefc70a48b2a803db265d6f6985521bc", code=INSUFFICIENT_FUNDS, version=providers/0.1.0)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at checkError (json-rpc-provider.js:95:1)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:605:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js:6:42)
```

**Comment by jdowning100** [comment]
Good catch thank you. Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/59
