### ISSUE TITLE
Cannot import recovery phrase - KeyringService must be unlocked.

### ISSUE THREAD

**Issue by Djadih** [PelagusWallet/pelagus-extension#91]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

I just installed the extension, then went to "use existing wallet"
Then entered a wallet password
Then put in my recovery phrase
Then when I click import, it doesn't do anything.

### What did not work?

I click "import account" after putting in my seed phrase, and nothing happens.
v0.2.2

### Version

None

### Relevant log output

```shell
logger.ts:203  ❌ [17:34:21.550] DoggoService.internalStartService  [2023-09-26]
logger.ts:209 No Ethereum provider available, not setting up DOGGO monitoring...
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:21.551] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:84796:24  [2023-09-26]
logger.ts:209 Async thunk failed Error: KeyringService must be unlocked.
    at KeyringService.requireUnlocked (index.ts:286:13)
    at KeyringService.importKeyring (index.ts:343:10)
    at main.ts:1355:35
    at index.js:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.js:304:23)
    at async keyrings.ts:56:65
    at async utils.ts:129:9
logEvent @ logger.ts:209
logger.ts:203  🐛 [17:34:21.552] TelemetryService.checkStorageUsage  [2023-09-26]
index.ts:308 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getDevices')
    at LedgerService.refreshConnectedLedger (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:101151:54)
    at LedgerService.internalStartService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:101141:16)
    at async LedgerService.startService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:66210:15)
    at async Promise.all (index 10)
    at async Main.internalStartService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:114462:11)
    at async Main.startService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:66210:15)
index.ts:296 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at LedgerService.internalStartService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:101142:25)
    at async LedgerService.startService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:66210:15)
    at async Promise.all (index 10)
    at async Main.internalStartService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:114462:11)
    at async Main.startService (chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:66210:15)
main.ts:738 Shard set to cyprus-1
serial-fallback-provider.ts:1037 Provider not found in map, creating new provider...
logger.ts:203  🐛 [17:34:21.571] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.571] SerialFallbackProvider.reconnectProvider  [2023-09-26]
serial-fallback-provider.ts:1037 Provider not found in map, creating new provider...
logger.ts:203  🐛 [17:34:21.572] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.572] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.572] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.572] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.579] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:21.580] SerialFallbackProvider.routeRpcCall  [2023-09-26]
index.js:224 Uncaught (in promise) Error: could not detect context (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at JsonRpcProvider.<anonymous> (json-rpc-provider.js:470:27)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js:6:57)
logger.ts:203  ❌ [17:34:21.581] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 800 ms. URL: http://localhost:8610
logEvent @ logger.ts:209
logger.ts:203  🐛 [17:34:21.625] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.626] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.628] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.628] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:21.628] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 800 ms. URL: http://localhost:8610
logEvent @ logger.ts:209
logger.ts:203  🐛 [17:34:21.634] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:21.635] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:21.635] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.635] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.635] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.636] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.636] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.636] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:21.681] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:21.686] SerialFallbackProvider.routeRpcCall  [2023-09-26]
index.js:224 Uncaught (in promise) Error: could not detect context (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at JsonRpcProvider.<anonymous> (json-rpc-provider.js:470:27)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js:6:57)
logger.ts:203  🐛 [17:34:21.695] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:21.699] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  ❌ [17:34:21.752] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 800 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:21.752] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 1600 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:21.753] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 800 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:21.753] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 1600 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:21.754] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 3200 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:21.754] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 6400 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  🐛 [17:34:22.234] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.271] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.275] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.291] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.296] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.302] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.306] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.352] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.357] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.358] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.359] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.363] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.403] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.461] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.481] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.546] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.815] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.820] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.957] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.962] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:22.996] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:22.999] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.044] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.051] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.063] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.074] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.079] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.093] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.114] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.115] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.119] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.170] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.358] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.364] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.365] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.365] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:23.365] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 1600 ms. URL: http://localhost:8610
logEvent @ logger.ts:209
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
index.js:224 Uncaught (in promise) Error: could not detect context (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:470:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
logger.ts:203  🐛 [17:34:23.387] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.391] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.391] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.392] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:23.392] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 1600 ms. URL: http://localhost:8610
logEvent @ logger.ts:209
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.402] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.494] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.502] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.514] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
index.js:224 Uncaught (in promise) Error: could not detect context (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:470:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
logger.ts:203  🐛 [17:34:23.555] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.589] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.606] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.607] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.607] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:23.607] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 10000 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.661] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
index.js:224 Uncaught (in promise) Error: could not detect context (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:470:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
logger.ts:203  🐛 [17:34:23.697] SerialFallbackProvider.routeRpcCall  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.717] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.717] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:23.718] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:23.718] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 3200 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
logger.ts:203  🐛 [17:34:23.753] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
index.js:224 Uncaught (in promise) Error: could not detect context (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:470:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:23.833] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:23.838] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:23.869] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:24.125] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:24.131] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:24.131] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:24.187] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:24.351] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:24.402] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:24.469] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:24.474] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:24.575] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:24.577] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:24.970] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:25.020] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:25.103] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
logger.ts:203  🐛 [17:34:25.162] SerialFallbackProvider.routeRpcCall  [2023-09-26]
logger.ts:203  🐛 [17:34:25.252] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:25.257] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:25.257] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:25.257] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:25.257] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 3200 ms. URL: http://localhost:8610
logEvent @ logger.ts:209
logger.ts:203  🐛 [17:34:25.258] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:25.264] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:25.265] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:25.265] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:25.265] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 3200 ms. URL: http://localhost:8610
logEvent @ logger.ts:209
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:25.541] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  🐛 [17:34:25.593] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:25.594] SerialFallbackProvider.disconnectCurrentProvider  [2023-09-26]
logger.ts:203  🐛 [17:34:25.594] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:203  ❌ [17:34:25.595] SerialFallbackProvider.reconnectProvider  [2023-09-26]
logger.ts:209 Could not detect network; trying again in 10000 ms. URL: https://rpc.cyprus1.colosseum.quaiscan.io
logEvent @ logger.ts:209
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  ❌ [17:34:25.656] ChainService.fetchLatestBlockForNetwork  [2023-09-26]
logger.ts:209 Error getting block number Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:452:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
logEvent @ logger.ts:209
index.js:224 Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:452:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
index.js:224 Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/0.1.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at SerialFallbackProvider.<anonymous> (json-rpc-provider.js:452:27)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.js:5:58)
logger.ts:203  🐛 [17:34:25.904] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:81317:30  [2023-09-26]
serial-fallback-provider.ts:364 console.trace
routeRpcCall @ serial-fallback-provider.ts:364
logger.ts:203  ❌ [17:34:32.321] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:84796:24  [2023-09-26]
logger.ts:209 Async thunk failed Error: KeyringService must be unlocked.
    at KeyringService.requireUnlocked (index.ts:286:13)
    at KeyringService.importKeyring (index.ts:343:10)
    at main.ts:1355:35
    at index.js:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.js:304:23)
    at async keyrings.ts:56:65
    at async utils.ts:129:9
logEvent @ logger.ts:209
logger.ts:203  ❌ [17:34:50.425] chrome-extension://gaegollnpijhedifeeeepdoffkgfcmbc/background.js:84796:24  [2023-09-26]
logger.ts:209 Async thunk failed Error: KeyringService must be unlocked.
    at KeyringService.requireUnlocked (index.ts:286:13)
    at KeyringService.importKeyring (index.ts:343:10)
    at main.ts:1355:35
    at index.js:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.js:304:23)
    at async keyrings.ts:56:65
    at async utils.ts:129:9
logEvent @ logger.ts:209
```

**Comment by robschleusner** [comment]
Unable to recreate

**Comment by Denis2626** [comment]
Also was unable to reproduce

**Comment by wizeguyy** [comment]
I believe I have a wallet to reproduce this
